#ruledef
{
    RST                       => 0x00
    STC                       => 0x01
    CLC                       => 0x02
    MOV $A, {im: i8}          => 0x03 @ im
    ADD $A, {im: i8}          => 0x04 @ im
    SUB $A, {im: i8}          => 0x05 @ im
    AND $A, {im: i8}          => 0x06 @ im
    OR $A, {im: i8}           => 0x07 @ im
    XOR $A, {im: i8}          => 0x08 @ im
    CMP $A, {im: i8}          => 0x09 @ im
    MOV $B, {im: i8}          => 0x0a @ im
    ADD $B, {im: i8}          => 0x0b @ im
    SUB $B, {im: i8}          => 0x0c @ im
    AND $B, {im: i8}          => 0x0d @ im
    OR $B, {im: i8}           => 0x0e @ im
    XOR $B, {im: i8}          => 0x0f @ im
    CMP $B, {im: i8}          => 0x10 @ im
    MOV $C, {im: i8}          => 0x11 @ im
    ADD $C, {im: i8}          => 0x12 @ im
    SUB $C, {im: i8}          => 0x13 @ im
    AND $C, {im: i8}          => 0x14 @ im
    OR $C, {im: i8}           => 0x15 @ im
    XOR $C, {im: i8}          => 0x16 @ im
    CMP $C, {im: i8}          => 0x17 @ im
    MOV $D, {im: i8}          => 0x18 @ im
    ADD $D, {im: i8}          => 0x19 @ im
    SUB $D, {im: i8}          => 0x1a @ im
    AND $D, {im: i8}          => 0x1b @ im
    OR $D, {im: i8}           => 0x1c @ im
    XOR $D, {im: i8}          => 0x1d @ im
    CMP $D, {im: i8}          => 0x1e @ im
    MOV $E, {im: i8}          => 0x1f @ im
    ADD $E, {im: i8}          => 0x20 @ im
    SUB $E, {im: i8}          => 0x21 @ im
    CMP $E, {im: i8}          => 0x22 @ im
    MOV $A, $E                => 0x23
    MOV $E, $A                => 0x24
    CMP $E, A                 => 0x25
    MOV $B, $E                => 0x26
    MOV $E, $B                => 0x27
    CMP $E, B                 => 0x28
    MOV $C, $E                => 0x29
    MOV $E, $C                => 0x2a
    CMP $E, C                 => 0x2b
    MOV $D, $E                => 0x2c
    MOV $E, $D                => 0x2d
    CMP $E, D                 => 0x2e
    MOV $CLK, {im: i8}        => 0x2f @ im
    MOV $CLK, $E              => 0x30
    MOV $A, $B                => 0x31
    ADD $A, $B                => 0x32
    SUB $A, $B                => 0x33
    AND $A, $B                => 0x34
    OR $A, $B                 => 0x35
    XOR $A, $B                => 0x36
    CMP $A, $B                => 0x37
    MOV $A, $C                => 0x38
    ADD $A, $C                => 0x39
    SUB $A, $C                => 0x3a
    AND $A, $C                => 0x3b
    OR $A, $C                 => 0x3c
    XOR $A, $C                => 0x3d
    CMP $A, $C                => 0x3e
    MOV $A, $D                => 0x3f
    ADD $A, $D                => 0x40
    SUB $A, $D                => 0x41
    AND $A, $D                => 0x42
    OR $A, $D                 => 0x43
    XOR $A, $D                => 0x44
    CMP $A, $D                => 0x45
    MOV $B, $A                => 0x46
    ADD $B, $A                => 0x47
    SUB $B, $A                => 0x48
    AND $B, $A                => 0x49
    OR $B, $A                 => 0x4a
    XOR $B, $A                => 0x4b
    CMP $B, $A                => 0x4c
    MOV $B, $C                => 0x4d
    ADD $B, $C                => 0x4e
    SUB $B, $C                => 0x4f
    AND $B, $C                => 0x50
    OR $B, $C                 => 0x51
    XOR $B, $C                => 0x52
    CMP $B, $C                => 0x53
    MOV $B, $D                => 0x54
    ADD $B, $D                => 0x55
    SUB $B, $D                => 0x56
    AND $B, $D                => 0x57
    OR $B, $D                 => 0x58
    XOR $B, $D                => 0x59
    CMP $B, $D                => 0x5a
    MOV $C, $A                => 0x5b
    ADD $C, $A                => 0x5c
    SUB $C, $A                => 0x5d
    AND $C, $A                => 0x5e
    OR $C, $A                 => 0x5f
    XOR $C, $A                => 0x60
    CMP $C, $A                => 0x61
    MOV $C, $B                => 0x62
    ADD $C, $B                => 0x63
    SUB $C, $B                => 0x64
    AND $C, $B                => 0x65
    OR $C, $B                 => 0x66
    XOR $C, $B                => 0x67
    CMP $C, $B                => 0x68
    MOV $C, $D                => 0x69
    ADD $C, $D                => 0x6a
    SUB $C, $D                => 0x6b
    AND $C, $D                => 0x6c
    OR $C, $D                 => 0x6d
    XOR $C, $D                => 0x6e
    CMP $C, $D                => 0x6f
    MOV $D, $A                => 0x70
    ADD $D, $A                => 0x71
    SUB $D, $A                => 0x72
    AND $D, $A                => 0x73
    OR $D, $A                 => 0x74
    XOR $D, $A                => 0x75
    CMP $D, $A                => 0x76
    MOV $D, $B                => 0x77
    ADD $D, $B                => 0x78
    SUB $D, $B                => 0x79
    AND $D, $B                => 0x7a
    OR $D, $B                 => 0x7b
    XOR $D, $B                => 0x7c
    CMP $D, $B                => 0x7d
    MOV $D, $C                => 0x7e
    ADD $D, $C                => 0x7f
    SUB $D, $C                => 0x80
    AND $D, $C                => 0x81
    OR $D, $C                 => 0x82
    XOR $D, $C                => 0x83
    CMP $D, $C                => 0x84
    MOV $A, [$CD]             => 0x85
    MOV [$CD], $A             => 0x86
    ADD $A, [$CD]             => 0x87
    SUB $A, [$CD]             => 0x88
    AND $A, [$CD]             => 0x89
    OR $A, [$CD]              => 0x8a
    XOR $A, [$CD]             => 0x8b
    CMP $A, [$CD]             => 0x8c
    MOV $B, [$CD]             => 0x8d
    MOV [$CD], $B             => 0x8e
    ADD $B, [$CD]             => 0x8f
    SUB $B, [$CD]             => 0x90
    AND $B, [$CD]             => 0x91
    OR $B, [$CD]              => 0x92
    XOR $B, [$CD]             => 0x93
    CMP $B, [$CD]             => 0x94
    MOV $C, [$CD]             => 0x95
    MOV [$CD], $C             => 0x96
    ADD $C, [$CD]             => 0x97
    SUB $C, [$CD]             => 0x98
    AND $C, [$CD]             => 0x99
    OR $C, [$CD]              => 0x9a
    XOR $C, [$CD]             => 0x9b
    CMP $C, [$CD]             => 0x9c
    MOV $D, [$CD]             => 0x9d
    MOV [$CD], $D             => 0x9e
    ADD $D, [$CD]             => 0x9f
    SUB $D, [$CD]             => 0xa0
    AND $D, [$CD]             => 0xa1
    OR $D, [$CD]              => 0xa2
    XOR $D, [$CD]             => 0xa3
    CMP $D, [$CD]             => 0xa4
    MOV $A, {address: u16}    => 0xa5 @ address[7:0] @ address[15:8]
    MOV $A, {address: u16} @be => 0xa5 @ address[15:8] @ address[7:0]
    MOV {address: u16}, $A    => 0xa6 @ address[7:0] @ address[15:8]
    MOV {address: u16}, $A @be => 0xa6 @ address[15:8] @ address[7:0]
    ADD $A, {address: u16}    => 0xa7 @ address[7:0] @ address[15:8]
    ADD $A, {address: u16} @be => 0xa7 @ address[15:8] @ address[7:0]
    SUB $A, {address: u16}    => 0xa8 @ address[7:0] @ address[15:8]
    SUB $A, {address: u16} @be => 0xa8 @ address[15:8] @ address[7:0]
    AND $A, {address: u16}    => 0xa9 @ address[7:0] @ address[15:8]
    AND $A, {address: u16} @be => 0xa9 @ address[15:8] @ address[7:0]
    OR $A, {address: u16}     => 0xaa @ address[7:0] @ address[15:8]
    OR $A, {address: u16} @be => 0xaa @ address[15:8] @ address[7:0]
    XOR $A, {address: u16}    => 0xab @ address[7:0] @ address[15:8]
    XOR $A, {address: u16} @be => 0xab @ address[15:8] @ address[7:0]
    CMP $A, {address: u16}    => 0xac @ address[7:0] @ address[15:8]
    CMP $A, {address: u16} @be => 0xac @ address[15:8] @ address[7:0]
    MOV $B, {address: u16}    => 0xad @ address[7:0] @ address[15:8]
    MOV $B, {address: u16} @be => 0xad @ address[15:8] @ address[7:0]
    MOV {address: u16}, $B    => 0xae @ address[7:0] @ address[15:8]
    MOV {address: u16}, $B @be => 0xae @ address[15:8] @ address[7:0]
    ADD $B, {address: u16}    => 0xaf @ address[7:0] @ address[15:8]
    ADD $B, {address: u16} @be => 0xaf @ address[15:8] @ address[7:0]
    SUB $B, {address: u16}    => 0xb0 @ address[7:0] @ address[15:8]
    SUB $B, {address: u16} @be => 0xb0 @ address[15:8] @ address[7:0]
    AND $B, {address: u16}    => 0xb1 @ address[7:0] @ address[15:8]
    AND $B, {address: u16} @be => 0xb1 @ address[15:8] @ address[7:0]
    OR $B, {address: u16}     => 0xb2 @ address[7:0] @ address[15:8]
    OR $B, {address: u16} @be => 0xb2 @ address[15:8] @ address[7:0]
    XOR $B, {address: u16}    => 0xb3 @ address[7:0] @ address[15:8]
    XOR $B, {address: u16} @be => 0xb3 @ address[15:8] @ address[7:0]
    CMP $B, {address: u16}    => 0xb4 @ address[7:0] @ address[15:8]
    CMP $B, {address: u16} @be => 0xb4 @ address[15:8] @ address[7:0]
    MOV $C, {address: u16}    => 0xb5 @ address[7:0] @ address[15:8]
    MOV $C, {address: u16} @be => 0xb5 @ address[15:8] @ address[7:0]
    MOV {address: u16}, $C    => 0xb6 @ address[7:0] @ address[15:8]
    MOV {address: u16}, $C @be => 0xb6 @ address[15:8] @ address[7:0]
    ADD $C, {address: u16}    => 0xb7 @ address[7:0] @ address[15:8]
    ADD $C, {address: u16} @be => 0xb7 @ address[15:8] @ address[7:0]
    SUB $C, {address: u16}    => 0xb8 @ address[7:0] @ address[15:8]
    SUB $C, {address: u16} @be => 0xb8 @ address[15:8] @ address[7:0]
    AND $C, {address: u16}    => 0xb9 @ address[7:0] @ address[15:8]
    AND $C, {address: u16} @be => 0xb9 @ address[15:8] @ address[7:0]
    OR $C, {address: u16}     => 0xba @ address[7:0] @ address[15:8]
    OR $C, {address: u16} @be => 0xba @ address[15:8] @ address[7:0]
    XOR $C, {address: u16}    => 0xbb @ address[7:0] @ address[15:8]
    XOR $C, {address: u16} @be => 0xbb @ address[15:8] @ address[7:0]
    CMP $C, {address: u16}    => 0xbc @ address[7:0] @ address[15:8]
    CMP $C, {address: u16} @be => 0xbc @ address[15:8] @ address[7:0]
    MOV $D, {address: u16}    => 0xbd @ address[7:0] @ address[15:8]
    MOV $D, {address: u16} @be => 0xbd @ address[15:8] @ address[7:0]
    MOV {address: u16}, $D    => 0xbe @ address[7:0] @ address[15:8]
    MOV {address: u16}, $D @be => 0xbe @ address[15:8] @ address[7:0]
    ADD $D, {address: u16}    => 0xbf @ address[7:0] @ address[15:8]
    ADD $D, {address: u16} @be => 0xbf @ address[15:8] @ address[7:0]
    SUB $D, {address: u16}    => 0xc0 @ address[7:0] @ address[15:8]
    SUB $D, {address: u16} @be => 0xc0 @ address[15:8] @ address[7:0]
    AND $D, {address: u16}    => 0xc1 @ address[7:0] @ address[15:8]
    AND $D, {address: u16} @be => 0xc1 @ address[15:8] @ address[7:0]
    OR $D, {address: u16}     => 0xc2 @ address[7:0] @ address[15:8]
    OR $D, {address: u16} @be => 0xc2 @ address[15:8] @ address[7:0]
    XOR $D, {address: u16}    => 0xc3 @ address[7:0] @ address[15:8]
    XOR $D, {address: u16} @be => 0xc3 @ address[15:8] @ address[7:0]
    CMP $D, {address: u16}    => 0xc4 @ address[7:0] @ address[15:8]
    CMP $D, {address: u16} @be => 0xc4 @ address[15:8] @ address[7:0]
    SDL $A                    => 0xc5
    SDL $B                    => 0xc6
    SDH $A                    => 0xc7
    SDH $B                    => 0xc8
    OUT {im: i8}, $A          => 0xc9 @ im
    INP $A, {im: i8}          => 0xca @ im
    OUT $B, $A                => 0xcb
    INP $A, $B                => 0xcc
    OLR                       => 0xcd
    OLD {im: i8}              => 0xce @ im
    OLC {im: i8}              => 0xcf @ im
    OLD $A                    => 0xd0
    OLD $B                    => 0xd1
    OLC $A                    => 0xd2
    OLC $B                    => 0xd3
    LSL $A                    => 0xd4
    LSL $B                    => 0xd5
    LSL $C                    => 0xd6
    LSL $D                    => 0xd7
    LSL {address: u16}        => 0xd8 @ address[7:0] @ address[15:8]
    LSL {address: u16} @be    => 0xd8 @ address[15:8] @ address[7:0]
    LSL [$CD]                 => 0xd9
    LSR $A                    => 0xda
    LSR $B                    => 0xdb
    LSR $C                    => 0xdc
    LSR $D                    => 0xdd
    LSR {address: u16}        => 0xde @ address[7:0] @ address[15:8]
    LSR {address: u16} @be    => 0xde @ address[15:8] @ address[7:0]
    LSR [$CD]                 => 0xdf
    PSH $A                    => 0xe0
    PUL $A                    => 0xe1
    PSH $B                    => 0xe2
    PUL $B                    => 0xe3
    PSH $C                    => 0xe4
    PUL $C                    => 0xe5
    PSH $D                    => 0xe6
    PUL $D                    => 0xe7
    PSF                       => 0xe8
    PLF                       => 0xe9
    MOV $SP, $CD              => 0xea
    MOV $CD, $SP              => 0xeb
    JMP {address: u16}        => 0xec @ address[7:0] @ address[15:8]
    JMP {address: u16} @be    => 0xec @ address[15:8] @ address[7:0]
    JSR {address: u16}        => 0xed @ address[7:0] @ address[15:8]
    JSR {address: u16} @be    => 0xed @ address[15:8] @ address[7:0]
    JMP [$CD]                 => 0xee
    JSR [$CD]                 => 0xef
    RTS                       => 0xf0
    JZ {address: u16}         => 0xf1 @ address[7:0] @ address[15:8]
    JZ {address: u16} @be     => 0xf1 @ address[15:8] @ address[7:0]
    JO {address: u16}         => 0xf2 @ address[7:0] @ address[15:8]
    JO {address: u16} @be     => 0xf2 @ address[15:8] @ address[7:0]
    JN {address: u16}         => 0xf3 @ address[7:0] @ address[15:8]
    JN {address: u16} @be     => 0xf3 @ address[15:8] @ address[7:0]
    JC {address: u16}         => 0xf4 @ address[7:0] @ address[15:8]
    JC {address: u16} @be     => 0xf4 @ address[15:8] @ address[7:0]
    JNZ {address: u16}        => 0xf5 @ address[7:0] @ address[15:8]
    JNZ {address: u16} @be    => 0xf5 @ address[15:8] @ address[7:0]
    JNO {address: u16}        => 0xf6 @ address[7:0] @ address[15:8]
    JNO {address: u16} @be    => 0xf6 @ address[15:8] @ address[7:0]
    JP {address: u16}         => 0xf7 @ address[7:0] @ address[15:8]
    JP {address: u16} @be     => 0xf7 @ address[15:8] @ address[7:0]
    JNC {address: u16}        => 0xf8 @ address[7:0] @ address[15:8]
    JNC {address: u16} @be    => 0xf8 @ address[15:8] @ address[7:0]
    JGZ {address: u16}        => 0xf9 @ address[7:0] @ address[15:8]
    JGZ {address: u16} @be    => 0xf9 @ address[15:8] @ address[7:0]
    SII                       => 0xfa
    CII                       => 0xfb
    ITR                       => 0xfc
    RTI                       => 0xfd
    NOP                       => 0xfe
    HLT                       => 0xff
}
