#ruledef
{
    RST   => 0x00 
    STC   => 0x01 
    CLC   => 0x02 
    MOV  $A,  {im: i8} => 0x03 @ im
    ADD  $A,  {im: i8} => 0x04 @ im
    SUB  $A,  {im: i8} => 0x05 @ im
    AND  $A,  {im: i8} => 0x06 @ im
    OR   $A,  {im: i8} => 0x07 @ im
    XOR  $A,  {im: i8} => 0x08 @ im
    CMP  $A,  {im: i8} => 0x09 @ im
    MOV  $B,  {im: i8} => 0x0a @ im
    ADD  $B,  {im: i8} => 0x0b @ im
    SUB  $B,  {im: i8} => 0x0c @ im
    AND  $B,  {im: i8} => 0x0d @ im
    OR   $B,  {im: i8} => 0x0e @ im
    XOR  $B,  {im: i8} => 0x0f @ im
    CMP  $B,  {im: i8} => 0x10 @ im
    MOV  $C,  {im: i8} => 0x11 @ im
    ADD  $C,  {im: i8} => 0x12 @ im
    SUB  $C,  {im: i8} => 0x13 @ im
    AND  $C,  {im: i8} => 0x14 @ im
    OR   $C,  {im: i8} => 0x15 @ im
    XOR  $C,  {im: i8} => 0x16 @ im
    CMP  $C,  {im: i8} => 0x17 @ im
    MOV  $D,  {im: i8} => 0x18 @ im
    ADD  $D,  {im: i8} => 0x19 @ im
    SUB  $D,  {im: i8} => 0x1a @ im
    AND  $D,  {im: i8} => 0x1b @ im
    OR   $D,  {im: i8} => 0x1c @ im
    XOR  $D,  {im: i8} => 0x1d @ im
    CMP  $D,  {im: i8} => 0x1e @ im
    MOV  $E,  {im: i8} => 0x1f @ im
    ADD  $E,  {im: i8} => 0x20 @ im
    SUB  $E,  {im: i8} => 0x21 @ im
    CMP  $E,  {im: i8} => 0x22 @ im
    MOV  $A,  $E    => 0x23 
    MOV  $E,  $A    => 0x24 
    CMP  $E,  A     => 0x25 
    MOV  $B,  $E    => 0x26 
    MOV  $E,  $B    => 0x27 
    CMP  $E,  B     => 0x28 
    MOV  $C,  $E    => 0x29 
    MOV  $E,  $C    => 0x2a 
    CMP  $E,  C     => 0x2b 
    MOV  $D,  $E    => 0x2c 
    MOV  $E,  $D    => 0x2d 
    CMP  $E,  D     => 0x2e 
    MOV  $CLK,{im: i8} => 0x2f @ im
    MOV  $CLK,$E    => 0x30 
    MOV  $A,  $B    => 0x31 
    ADD  $A,  $B    => 0x32 
    SUB  $A,  $B    => 0x33 
    AND  $A,  $B    => 0x34 
    OR   $A,  $B    => 0x35 
    XOR  $A,  $B    => 0x36 
    CMP  $A,  $B    => 0x37 
    MOV  $A,  $C    => 0x38 
    ADD  $A,  $C    => 0x39 
    SUB  $A,  $C    => 0x3a 
    AND  $A,  $C    => 0x3b 
    OR   $A,  $C    => 0x3c 
    XOR  $A,  $C    => 0x3d 
    CMP  $A,  $C    => 0x3e 
    MOV  $A,  $D    => 0x3f 
    ADD  $A,  $D    => 0x40 
    SUB  $A,  $D    => 0x41 
    AND  $A,  $D    => 0x42 
    OR   $A,  $D    => 0x43 
    XOR  $A,  $D    => 0x44 
    CMP  $A,  $D    => 0x45 
    MOV  $B,  $A    => 0x46 
    ADD  $B,  $A    => 0x47 
    SUB  $B,  $A    => 0x48 
    AND  $B,  $A    => 0x49 
    OR   $B,  $A    => 0x4a 
    XOR  $B,  $A    => 0x4b 
    CMP  $B,  $A    => 0x4c 
    MOV  $B,  $C    => 0x4d 
    ADD  $B,  $C    => 0x4e 
    SUB  $B,  $C    => 0x4f 
    AND  $B,  $C    => 0x50 
    OR   $B,  $C    => 0x51 
    XOR  $B,  $C    => 0x52 
    CMP  $B,  $C    => 0x53 
    MOV  $B,  $D    => 0x54 
    ADD  $B,  $D    => 0x55 
    SUB  $B,  $D    => 0x56 
    AND  $B,  $D    => 0x57 
    OR   $B,  $D    => 0x58 
    XOR  $B,  $D    => 0x59 
    CMP  $B,  $D    => 0x5a 
    MOV  $C,  $A    => 0x5b 
    ADD  $C,  $A    => 0x5c 
    SUB  $C,  $A    => 0x5d 
    AND  $C,  $A    => 0x5e 
    OR   $C,  $A    => 0x5f 
    XOR  $C,  $A    => 0x60 
    CMP  $C,  $A    => 0x61 
    MOV  $C,  $B    => 0x62 
    ADD  $C,  $B    => 0x63 
    SUB  $C,  $B    => 0x64 
    AND  $C,  $B    => 0x65 
    OR   $C,  $B    => 0x66 
    XOR  $C,  $B    => 0x67 
    CMP  $C,  $B    => 0x68 
    MOV  $C,  $D    => 0x69 
    ADD  $C,  $D    => 0x6a 
    SUB  $C,  $D    => 0x6b 
    AND  $C,  $D    => 0x6c 
    OR   $C,  $D    => 0x6d 
    XOR  $C,  $D    => 0x6e 
    CMP  $C,  $D    => 0x6f 
    MOV  $D,  $A    => 0x70 
    ADD  $D,  $A    => 0x71 
    SUB  $D,  $A    => 0x72 
    AND  $D,  $A    => 0x73 
    OR   $D,  $A    => 0x74 
    XOR  $D,  $A    => 0x75 
    CMP  $D,  $A    => 0x76 
    MOV  $D,  $B    => 0x77 
    ADD  $D,  $B    => 0x78 
    SUB  $D,  $B    => 0x79 
    AND  $D,  $B    => 0x7a 
    OR   $D,  $B    => 0x7b 
    XOR  $D,  $B    => 0x7c 
    CMP  $D,  $B    => 0x7d 
    MOV  $D,  $C    => 0x7e 
    ADD  $D,  $C    => 0x7f 
    SUB  $D,  $C    => 0x80 
    AND  $D,  $C    => 0x81 
    OR   $D,  $C    => 0x82 
    XOR  $D,  $C    => 0x83 
    CMP  $D,  $C    => 0x84 
    MOV  $A,  [$CD] => 0x85 
    MOV  [$CD],$A    => 0x86 
    ADD  $A,  [$CD] => 0x87 
    SUB  $A,  [$CD] => 0x88 
    AND  $A,  [$CD] => 0x89 
    OR   $A,  [$CD] => 0x8a 
    XOR  $A,  [$CD] => 0x8b 
    CMP  $A,  [$CD] => 0x8c 
    MOV  $B,  [$CD] => 0x8d 
    MOV  [$CD],$B    => 0x8e 
    ADD  $B,  [$CD] => 0x8f 
    SUB  $B,  [$CD] => 0x90 
    AND  $B,  [$CD] => 0x91 
    OR   $B,  [$CD] => 0x92 
    XOR  $B,  [$CD] => 0x93 
    CMP  $B,  [$CD] => 0x94 
    MOV  $C,  [$CD] => 0x95 
    MOV  [$CD],$C    => 0x96 
    ADD  $C,  [$CD] => 0x97 
    SUB  $C,  [$CD] => 0x98 
    AND  $C,  [$CD] => 0x99 
    OR   $C,  [$CD] => 0x9a 
    XOR  $C,  [$CD] => 0x9b 
    CMP  $C,  [$CD] => 0x9c 
    MOV  $D,  [$CD] => 0x9d 
    MOV  [$CD],$D    => 0x9e 
    ADD  $D,  [$CD] => 0x9f 
    SUB  $D,  [$CD] => 0xa0 
    AND  $D,  [$CD] => 0xa1 
    OR   $D,  [$CD] => 0xa2 
    XOR  $D,  [$CD] => 0xa3 
    CMP  $D,  [$CD] => 0xa4 
    MOV  $A,  {address: u16} => 0xa5 @ le(address)
    MOV  {address: u16},$A    => 0xa6 @ le(address)
    ADD  $A,  {address: u16} => 0xa7 @ le(address)
    SUB  $A,  {address: u16} => 0xa8 @ le(address)
    AND  $A,  {address: u16} => 0xa9 @ le(address)
    OR   $A,  {address: u16} => 0xaa @ le(address)
    XOR  $A,  {address: u16} => 0xab @ le(address)
    CMP  $A,  {address: u16} => 0xac @ le(address)
    MOV  $B,  {address: u16} => 0xad @ le(address)
    MOV  {address: u16},$B    => 0xae @ le(address)
    ADD  $B,  {address: u16} => 0xaf @ le(address)
    SUB  $B,  {address: u16} => 0xb0 @ le(address)
    AND  $B,  {address: u16} => 0xb1 @ le(address)
    OR   $B,  {address: u16} => 0xb2 @ le(address)
    XOR  $B,  {address: u16} => 0xb3 @ le(address)
    CMP  $B,  {address: u16} => 0xb4 @ le(address)
    MOV  $C,  {address: u16} => 0xb5 @ le(address)
    MOV  {address: u16},$C    => 0xb6 @ le(address)
    ADD  $C,  {address: u16} => 0xb7 @ le(address)
    SUB  $C,  {address: u16} => 0xb8 @ le(address)
    AND  $C,  {address: u16} => 0xb9 @ le(address)
    OR   $C,  {address: u16} => 0xba @ le(address)
    XOR  $C,  {address: u16} => 0xbb @ le(address)
    CMP  $C,  {address: u16} => 0xbc @ le(address)
    MOV  $D,  {address: u16} => 0xbd @ le(address)
    MOV  {address: u16},$D    => 0xbe @ le(address)
    ADD  $D,  {address: u16} => 0xbf @ le(address)
    SUB  $D,  {address: u16} => 0xc0 @ le(address)
    AND  $D,  {address: u16} => 0xc1 @ le(address)
    OR   $D,  {address: u16} => 0xc2 @ le(address)
    XOR  $D,  {address: u16} => 0xc3 @ le(address)
    CMP  $D,  {address: u16} => 0xc4 @ le(address)
    SDL  $A    => 0xc5 
    SDL  $B    => 0xc6 
    SDH  $A    => 0xc7 
    SDH  $B    => 0xc8 
    OUT  #,   RA    => 0xc9 
    INP  RA,  {im: i8} => 0xca @ im
    OUT  RB,  RA    => 0xcb 
    INP  RA,  RB    => 0xcc 
    OLR   => 0xcd 
    OLD  {im: i8} => 0xce @ im
    OLC  {im: i8} => 0xcf @ im
    OLD  $A    => 0xd0 
    OLD  $B    => 0xd1 
    OLC  $A    => 0xd2 
    OLC  $B    => 0xd3 
    LSL  $A    => 0xd4 
    LSL  $B    => 0xd5 
    LSL  $C    => 0xd6 
    LSL  $D    => 0xd7 
    LSL  {address: u16} => 0xd8 @ le(address)
    LSL  [$CD] => 0xd9 
    LSR  $A    => 0xda 
    LSR  $B    => 0xdb 
    LSR  $C    => 0xdc 
    LSR  $D    => 0xdd 
    LSR  {address: u16} => 0xde @ le(address)
    LSR  [$CD] => 0xdf 
    PSH  $A    => 0xe0 
    PUL  $A    => 0xe1 
    PSH  $B    => 0xe2 
    PUL  $B    => 0xe3 
    PSH  $C    => 0xe4 
    PUL  $C    => 0xe5 
    PSH  $D    => 0xe6 
    PUL  $D    => 0xe7 
    PSF  $D    => 0xe8 
    PLF  $D    => 0xe9 
    MOV  $SP, $CD   => 0xea 
    MOV  $CD, $SP   => 0xeb 
    JMP  {address: u16} => 0xec @ le(address)
    JSR  {address: u16} => 0xed @ le(address)
    JMP  [$CD] => 0xee 
    JSR  [$CD] => 0xef 
    RTS   => 0xf0 
    JZ   {address: u16} => 0xf1 @ le(address)
    JO   {address: u16} => 0xf2 @ le(address)
    JN   {address: u16} => 0xf3 @ le(address)
    JC   {address: u16} => 0xf4 @ le(address)
    JNZ  {address: u16} => 0xf5 @ le(address)
    JNO  {address: u16} => 0xf6 @ le(address)
    JP   {address: u16} => 0xf7 @ le(address)
    JNC  {address: u16} => 0xf8 @ le(address)
    JGZ  {address: u16} => 0xf9 @ le(address)
    SII   => 0xfa 
    CII   => 0xfb 
    ITR   => 0xfc 
    RTI   => 0xfd 
    NOP   => 0xfe 
    HLT   => 0xff 
}