; ==========================================================
; oled_text_5x7.asm
; ==========================================================
; Generated by make_oled_text_5x7_library.py
; SSD1325 5x7 monitor text layer.
;
; Cell size:
;   6 pixels wide  = 3 grouped SSD1325 columns
;   8 pixels tall  = 8 font rows
;
; Pixel packing for OLED_INIT / A0h = 0x52:
;   left pixel  -> high nibble
;   right pixel -> low nibble
;
; API:
;   OLED5_SET_CURSOR
;   OLED5_DRAW_CHAR
;   OLED5_DRAW_STRING
;
; Calling convention:
;   OLED5_SET_CURSOR:
;       A = column
;       B = row
;
;   OLED5_DRAW_CHAR:
;       A = ASCII character
;
;   OLED5_DRAW_STRING:
;       CD = pointer to null-terminated RAM string
;       newline = 0x0A
;
;   This renderer uses fixed foreground/background bytes for
;   monitor text output.
; ==========================================================

OLED5_SET_CURSOR:
    ; in: A = col, B = row
    MOV OLED_CURSOR_COL, $A
    MOV OLED_CURSOR_ROW, $B
    RTS

OLED5_NEWLINE:
    ; Move to column 0.
    MOV $A, 0x00
    MOV OLED_CURSOR_COL, $A

    ; row++
    MOV $A, OLED_CURSOR_ROW
    CLC
    ADD $A, 0x01
    MOV OLED_CURSOR_ROW, $A

    ; If row == OLED5_MAX_ROWS, wrap back to row 0.
    STC
    CMP $A, OLED5_MAX_ROWS
    JZ OLED5_NEWLINE_WRAP_TOP

    RTS

OLED5_NEWLINE_WRAP_TOP:
    MOV $A, 0x00
    MOV OLED_CURSOR_ROW, $A
    RTS

OLED5_ADVANCE_CURSOR:
    ; col++
    MOV $A, OLED_CURSOR_COL
    CLC
    ADD $A, 0x01
    MOV OLED_CURSOR_COL, $A

    ; If col == OLED5_MAX_COLS, wrap to the next row.
    STC
    CMP $A, OLED5_MAX_COLS
    JZ OLED5_ADVANCE_CURSOR_WRAP

    RTS

OLED5_ADVANCE_CURSOR_WRAP:
    JSR OLED5_NEWLINE
    RTS

OLED5_CLEAR_CURRENT_LINE_LOOP:
    STC
    CMP $B, 0x00
    JZ OLED5_CLEAR_CURRENT_LINE_DONE

    JSR OLED5_CHAR_SPACE

    STC
    SUB $B, 0x01
    JMP OLED5_CLEAR_CURRENT_LINE_LOOP

OLED5_CLEAR_CURRENT_LINE_DONE:
    MOV $A, 0x00
    MOV OLED_CURSOR_COL, $A
    RTS

OLED5_INC_CD:
    CLC
    ADD $C, 0x01
    JNC OLED5_INC_CD_DONE

    CLC
    ADD $D, 0x01

OLED5_INC_CD_DONE:
    RTS

OLED5_DRAW_STRING:
OLED5_DRAW_STRING_LOOP:
    MOV $A, [$CD]

    STC
    CMP $A, 0x00
    JZ OLED5_DRAW_STRING_DONE

    STC
    CMP $A, 0x0A
    JZ OLED5_DRAW_STRING_NEWLINE

    JSR OLED5_DRAW_CHAR
    JSR OLED5_INC_CD
    JMP OLED5_DRAW_STRING_LOOP

OLED5_DRAW_STRING_NEWLINE:
    JSR OLED5_NEWLINE
    JSR OLED5_INC_CD
    JMP OLED5_DRAW_STRING_LOOP

OLED5_DRAW_STRING_DONE:
    RTS

OLED5_DRAW_CHAR:
    MOV OLED_CHAR_TMP, $A

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x20       ; SPACE
    JZ OLED5_CHAR_SPACE

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x30       ; 0
    JZ OLED5_CHAR_DIGIT_0

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x31       ; 1
    JZ OLED5_CHAR_DIGIT_1

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x32       ; 2
    JZ OLED5_CHAR_DIGIT_2

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x33       ; 3
    JZ OLED5_CHAR_DIGIT_3

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x34       ; 4
    JZ OLED5_CHAR_DIGIT_4

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x35       ; 5
    JZ OLED5_CHAR_DIGIT_5

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x36       ; 6
    JZ OLED5_CHAR_DIGIT_6

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x37       ; 7
    JZ OLED5_CHAR_DIGIT_7

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x38       ; 8
    JZ OLED5_CHAR_DIGIT_8

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x39       ; 9
    JZ OLED5_CHAR_DIGIT_9

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x41       ; A
    JZ OLED5_CHAR_A

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x42       ; B
    JZ OLED5_CHAR_B

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x43       ; C
    JZ OLED5_CHAR_C

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x44       ; D
    JZ OLED5_CHAR_D

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x45       ; E
    JZ OLED5_CHAR_E

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x46       ; F
    JZ OLED5_CHAR_F

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x47       ; G
    JZ OLED5_CHAR_G

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x48       ; H
    JZ OLED5_CHAR_H

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x49       ; I
    JZ OLED5_CHAR_I

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x4A       ; J
    JZ OLED5_CHAR_J

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x4B       ; K
    JZ OLED5_CHAR_K

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x4C       ; L
    JZ OLED5_CHAR_L

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x4D       ; M
    JZ OLED5_CHAR_M

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x4E       ; N
    JZ OLED5_CHAR_N

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x4F       ; O
    JZ OLED5_CHAR_O

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x50       ; P
    JZ OLED5_CHAR_P

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x51       ; Q
    JZ OLED5_CHAR_Q

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x52       ; R
    JZ OLED5_CHAR_R

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x53       ; S
    JZ OLED5_CHAR_S

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x54       ; T
    JZ OLED5_CHAR_T

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x55       ; U
    JZ OLED5_CHAR_U

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x56       ; V
    JZ OLED5_CHAR_V

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x57       ; W
    JZ OLED5_CHAR_W

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x58       ; X
    JZ OLED5_CHAR_X

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x59       ; Y
    JZ OLED5_CHAR_Y

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x5A       ; Z
    JZ OLED5_CHAR_Z

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x3D       ; =
    JZ OLED5_CHAR_EQUALS

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x24       ; $
    JZ OLED5_CHAR_DOLLAR

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x3E       ; >
    JZ OLED5_CHAR_GT

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x3A       ; :
    JZ OLED5_CHAR_COLON

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x2D       ; -
    JZ OLED5_CHAR_DASH

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x5F       ; _
    JZ OLED5_CHAR_UNDERSCORE

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x2E       ; .
    JZ OLED5_CHAR_DOT

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x2F       ; /
    JZ OLED5_CHAR_SLASH

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x61       ; a
    JZ OLED5_CHAR_LOWER_A

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x62       ; b
    JZ OLED5_CHAR_LOWER_B

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x63       ; c
    JZ OLED5_CHAR_LOWER_C

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x64       ; d
    JZ OLED5_CHAR_LOWER_D

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x65       ; e
    JZ OLED5_CHAR_LOWER_E

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x66       ; f
    JZ OLED5_CHAR_LOWER_F

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x67       ; g
    JZ OLED5_CHAR_LOWER_G

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x68       ; h
    JZ OLED5_CHAR_LOWER_H

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x69       ; i
    JZ OLED5_CHAR_LOWER_I

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x6A       ; j
    JZ OLED5_CHAR_LOWER_J

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x6B       ; k
    JZ OLED5_CHAR_LOWER_K

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x6C       ; l
    JZ OLED5_CHAR_LOWER_L

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x6D       ; m
    JZ OLED5_CHAR_LOWER_M

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x6E       ; n
    JZ OLED5_CHAR_LOWER_N

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x6F       ; o
    JZ OLED5_CHAR_LOWER_O

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x70       ; p
    JZ OLED5_CHAR_LOWER_P

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x71       ; q
    JZ OLED5_CHAR_LOWER_Q

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x72       ; r
    JZ OLED5_CHAR_LOWER_R

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x73       ; s
    JZ OLED5_CHAR_LOWER_S

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x74       ; t
    JZ OLED5_CHAR_LOWER_T

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x75       ; u
    JZ OLED5_CHAR_LOWER_U

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x76       ; v
    JZ OLED5_CHAR_LOWER_V

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x77       ; w
    JZ OLED5_CHAR_LOWER_W

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x78       ; x
    JZ OLED5_CHAR_LOWER_X

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x79       ; y
    JZ OLED5_CHAR_LOWER_Y

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x7A       ; z
    JZ OLED5_CHAR_LOWER_Z

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x21       ; !
    JZ OLED5_CHAR_EXCLAMATION

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x22       ; "
    JZ OLED5_CHAR_DOUBLE_QUOTE

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x23       ; #
    JZ OLED5_CHAR_HASH

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x25       ; %
    JZ OLED5_CHAR_PERCENT

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x26       ; &
    JZ OLED5_CHAR_AMPERSAND

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x27       ; '
    JZ OLED5_CHAR_APOSTROPHE

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x28       ; (
    JZ OLED5_CHAR_LPAREN

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x29       ; )
    JZ OLED5_CHAR_RPAREN

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x2A       ; *
    JZ OLED5_CHAR_ASTERISK

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x2B       ; +
    JZ OLED5_CHAR_PLUS

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x2C       ; ,
    JZ OLED5_CHAR_COMMA

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x3B       ; ;
    JZ OLED5_CHAR_SEMICOLON

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x3C       ; <
    JZ OLED5_CHAR_LT

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x3F       ; ?
    JZ OLED5_CHAR_QUESTION

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x40       ; @
    JZ OLED5_CHAR_AT

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x5B       ; [
    JZ OLED5_CHAR_LBRACKET

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x5C       ; \
    JZ OLED5_CHAR_BACKSLASH

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x5D       ; ]
    JZ OLED5_CHAR_RBRACKET

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x5E       ; ^
    JZ OLED5_CHAR_CARET

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x60       ; `
    JZ OLED5_CHAR_BACKTICK

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x7B       ; {
    JZ OLED5_CHAR_LBRACE

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x7C       ; |
    JZ OLED5_CHAR_PIPE

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x7D       ; }
    JZ OLED5_CHAR_RBRACE

    MOV $A, OLED_CHAR_TMP
    STC
    CMP $A, 0x7E       ; ~
    JZ OLED5_CHAR_TILDE

    ; Unsupported character: draw a space-sized blank cell.
    JMP OLED5_CHAR_SPACE

OLED5_COMPUTE_CURSOR_BASE:
    ; base grouped column = origin_x + col * 3
    MOV $A, OLED_TEXT_ORIGIN_X
    MOV $B, OLED_CURSOR_COL

OLED5_CURSOR_X_LOOP:
    STC
    CMP $B, 0x00
    JZ OLED5_CURSOR_X_DONE

    CLC
    ADD $A, 0x03

    STC
    SUB $B, 0x01
    JMP OLED5_CURSOR_X_LOOP

OLED5_CURSOR_X_DONE:
    MOV OLED_GLYPH_BASE_X, $A

    ; base row = origin_y + row * 8
    MOV $A, OLED_TEXT_ORIGIN_Y
    MOV $B, OLED_CURSOR_ROW

OLED5_CURSOR_Y_LOOP:
    STC
    CMP $B, 0x00
    JZ OLED5_CURSOR_Y_DONE

    CLC
    ADD $A, 0x08

    STC
    SUB $B, 0x01
    JMP OLED5_CURSOR_Y_LOOP

OLED5_CURSOR_Y_DONE:
    MOV OLED_GLYPH_BASE_Y, $A
    RTS

OLED5_RENDER_BEGIN:
    JSR OLED5_COMPUTE_CURSOR_BASE

    ; column window: 3 grouped columns
    MOV $A, 0x15
    OLC $A
    MOV $A, OLED_GLYPH_BASE_X
    OLC $A
    CLC
    ADD $A, 0x02
    OLC $A

    ; row window: 8 pixel rows
    MOV $A, 0x75
    OLC $A
    MOV $A, OLED_GLYPH_BASE_Y
    OLC $A
    CLC
    ADD $A, 0x07
    OLC $A

    ; begin GDDRAM burst
    MOV $A, 0x5C
    OLC $A
    RTS


; Character: SPACE (' ')
OLED5_CHAR_SPACE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 0
OLED5_CHAR_DIGIT_0:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 1
OLED5_CHAR_DIGIT_1:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 2
OLED5_CHAR_DIGIT_2:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 3
OLED5_CHAR_DIGIT_3:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 4
OLED5_CHAR_DIGIT_4:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 5
OLED5_CHAR_DIGIT_5:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 6
OLED5_CHAR_DIGIT_6:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 7
OLED5_CHAR_DIGIT_7:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 8
OLED5_CHAR_DIGIT_8:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: 9
OLED5_CHAR_DIGIT_9:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: A
OLED5_CHAR_A:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: B
OLED5_CHAR_B:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: C
OLED5_CHAR_C:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: D
OLED5_CHAR_D:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: E
OLED5_CHAR_E:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: F
OLED5_CHAR_F:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: G
OLED5_CHAR_G:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: H
OLED5_CHAR_H:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: I
OLED5_CHAR_I:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: J
OLED5_CHAR_J:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: K
OLED5_CHAR_K:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: L
OLED5_CHAR_L:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: M
OLED5_CHAR_M:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: N
OLED5_CHAR_N:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: O
OLED5_CHAR_O:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: P
OLED5_CHAR_P:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: Q
OLED5_CHAR_Q:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: R
OLED5_CHAR_R:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: S
OLED5_CHAR_S:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: T
OLED5_CHAR_T:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: U
OLED5_CHAR_U:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: V
OLED5_CHAR_V:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: W
OLED5_CHAR_W:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: X
OLED5_CHAR_X:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: Y
OLED5_CHAR_Y:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: Z
OLED5_CHAR_Z:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: =
OLED5_CHAR_EQUALS:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: $
OLED5_CHAR_DOLLAR:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: >
OLED5_CHAR_GT:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: :
OLED5_CHAR_COLON:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: -
OLED5_CHAR_DASH:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: _
OLED5_CHAR_UNDERSCORE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: .
OLED5_CHAR_DOT:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: /
OLED5_CHAR_SLASH:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: a
OLED5_CHAR_LOWER_A:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: b
OLED5_CHAR_LOWER_B:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: c
OLED5_CHAR_LOWER_C:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: d
OLED5_CHAR_LOWER_D:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: e
OLED5_CHAR_LOWER_E:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: f
OLED5_CHAR_LOWER_F:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: g
OLED5_CHAR_LOWER_G:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: h
OLED5_CHAR_LOWER_H:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: i
OLED5_CHAR_LOWER_I:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: j
OLED5_CHAR_LOWER_J:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: k
OLED5_CHAR_LOWER_K:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: l
OLED5_CHAR_LOWER_L:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: m
OLED5_CHAR_LOWER_M:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: n
OLED5_CHAR_LOWER_N:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: o
OLED5_CHAR_LOWER_O:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: p
OLED5_CHAR_LOWER_P:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: q
OLED5_CHAR_LOWER_Q:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: r
OLED5_CHAR_LOWER_R:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: s
OLED5_CHAR_LOWER_S:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: t
OLED5_CHAR_LOWER_T:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: u
OLED5_CHAR_LOWER_U:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: v
OLED5_CHAR_LOWER_V:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: w
OLED5_CHAR_LOWER_W:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: x
OLED5_CHAR_LOWER_X:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: y
OLED5_CHAR_LOWER_Y:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: z
OLED5_CHAR_LOWER_Z:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: !
OLED5_CHAR_EXCLAMATION:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: "
OLED5_CHAR_DOUBLE_QUOTE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: #
OLED5_CHAR_HASH:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: %
OLED5_CHAR_PERCENT:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: &
OLED5_CHAR_AMPERSAND:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: '
OLED5_CHAR_APOSTROPHE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: (
OLED5_CHAR_LPAREN:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: )
OLED5_CHAR_RPAREN:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: *
OLED5_CHAR_ASTERISK:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: +
OLED5_CHAR_PLUS:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: ,
OLED5_CHAR_COMMA:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: ;
OLED5_CHAR_SEMICOLON:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: <
OLED5_CHAR_LT:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: ?
OLED5_CHAR_QUESTION:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: @
OLED5_CHAR_AT:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: [
OLED5_CHAR_LBRACKET:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: \
OLED5_CHAR_BACKSLASH:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: ]
OLED5_CHAR_RBRACKET:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: ^
OLED5_CHAR_CARET:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: `
OLED5_CHAR_BACKTICK:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: {
OLED5_CHAR_LBRACE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: |
OLED5_CHAR_PIPE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: }
OLED5_CHAR_RBRACE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS

; Character: ~
OLED5_CHAR_TILDE:
    JSR OLED5_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED5_ADVANCE_CURSOR
    RTS
; ==========================================================
; Terminal helper routines
; ==========================================================

OLED5_HOME:
    MOV $A, 0x00
    MOV OLED_CURSOR_COL, $A
    MOV OLED_CURSOR_ROW, $A
    RTS

OLED5_SET_DEFAULT_ORIGIN:
    MOV $A, OLED5_DEFAULT_X
    MOV OLED_TEXT_ORIGIN_X, $A
    MOV $A, OLED5_DEFAULT_Y
    MOV OLED_TEXT_ORIGIN_Y, $A
    RTS

OLED5_CLEAR_TEXT_SCREEN:
    PSH $A
    PSH $B
    PSH $D

    MOV $A, 0x15
    OLC $A
    MOV $A, 0x00
    OLC $A
    MOV $A, 0x3F
    OLC $A

    MOV $A, 0x75
    OLC $A
    MOV $A, 0x00
    OLC $A
    MOV $A, 0x3F
    OLC $A

    MOV $A, 0x5C
    OLC $A

    MOV $A, 0x00
    MOV $D, OLED5_CLEAR_ROWS

.OLED5_CLEAR_TEXT_ROW:
    MOV $B, OLED5_CLEAR_COLS

.OLED5_CLEAR_TEXT_COL:
    OLD $A
    STC
    SUB $B, 0x01
    JNZ .OLED5_CLEAR_TEXT_COL

    STC
    SUB $D, 0x01
    JNZ .OLED5_CLEAR_TEXT_ROW

    PUL $D
    PUL $B
    PUL $A
    RTS

OLED5_PUTC:
    STC
    CMP $A, 0x0A
    JZ OLED5_PUTC_NEWLINE

    STC
    CMP $A, 0x0D
    JZ OLED5_PUTC_CR

    STC
    CMP $A, 0x08
    JZ OLED5_PUTC_BACKSPACE

    JSR OLED5_DRAW_CHAR
    RTS

OLED5_PUTC_NEWLINE:
    JSR OLED5_NEWLINE
    RTS

OLED5_PUTC_CR:
    JSR OLED5_CARRIAGE_RETURN
    RTS

OLED5_PUTC_BACKSPACE:
    JSR OLED5_BACKSPACE
    RTS

OLED5_CARRIAGE_RETURN:
    MOV $A, 0x00
    MOV OLED_CURSOR_COL, $A
    RTS

OLED5_BACKSPACE:
    MOV $A, OLED_CURSOR_COL
    STC
    CMP $A, 0x00
    JZ OLED5_BACKSPACE_DONE

    STC
    SUB $A, 0x01
    MOV OLED_CURSOR_COL, $A

    MOV $A, 0x20
    JSR OLED5_DRAW_CHAR

    MOV $A, OLED_CURSOR_COL
    STC
    SUB $A, 0x01
    MOV OLED_CURSOR_COL, $A

OLED5_BACKSPACE_DONE:
    RTS

OLED5_CLEAR_CURRENT_CELL_DIRECT:
    PSH $A
    PSH $B
    PSH $D

    MOV $A, OLED_CURSOR_COL
    MOV $B, $A
    CLC
    ADD $A, $B
    CLC
    ADD $A, $B
    CLC
    ADD $A, OLED_TEXT_ORIGIN_X
    MOV OLED_WIN_COL_START, $A
    CLC
    ADD $A, 0x02
    MOV OLED_WIN_COL_END, $A

    MOV $A, OLED_CURSOR_ROW
    LSL $A
    LSL $A
    LSL $A
    CLC
    ADD $A, OLED_TEXT_ORIGIN_Y
    MOV OLED_WIN_ROW_START, $A
    CLC
    ADD $A, 0x07
    MOV OLED_WIN_ROW_END, $A

    MOV $A, 0x15
    OLC $A
    MOV $A, OLED_WIN_COL_START
    OLC $A
    MOV $A, OLED_WIN_COL_END
    OLC $A

    MOV $A, 0x75
    OLC $A
    MOV $A, OLED_WIN_ROW_START
    OLC $A
    MOV $A, OLED_WIN_ROW_END
    OLC $A

    MOV $A, 0x5C
    OLC $A
    MOV $A, 0x00
    MOV $D, 0x08

.OLED5_CLEAR_CELL_ROW:
    MOV $B, 0x03

.OLED5_CLEAR_CELL_COL:
    OLD $A
    STC
    SUB $B, 0x01
    JNZ .OLED5_CLEAR_CELL_COL

    STC
    SUB $D, 0x01
    JNZ .OLED5_CLEAR_CELL_ROW

    PUL $D
    PUL $B
    PUL $A
    RTS

OLED5_DRAW_CURRENT_CELL_BLOCK_DIRECT:
    PSH $A
    PSH $B
    PSH $D

    MOV $A, OLED_CURSOR_COL
    MOV $B, $A
    CLC
    ADD $A, $B
    CLC
    ADD $A, $B
    CLC
    ADD $A, OLED_TEXT_ORIGIN_X
    MOV OLED_WIN_COL_START, $A
    CLC
    ADD $A, 0x02
    MOV OLED_WIN_COL_END, $A

    MOV $A, OLED_CURSOR_ROW
    LSL $A
    LSL $A
    LSL $A
    CLC
    ADD $A, OLED_TEXT_ORIGIN_Y
    MOV OLED_WIN_ROW_START, $A
    CLC
    ADD $A, 0x07
    MOV OLED_WIN_ROW_END, $A

    MOV $A, 0x15
    OLC $A
    MOV $A, OLED_WIN_COL_START
    OLC $A
    MOV $A, OLED_WIN_COL_END
    OLC $A

    MOV $A, 0x75
    OLC $A
    MOV $A, OLED_WIN_ROW_START
    OLC $A
    MOV $A, OLED_WIN_ROW_END
    OLC $A

    MOV $A, 0x5C
    OLC $A
    MOV $A, 0xFF
    MOV $D, 0x08

.OLED5_DRAW_CELL_BLOCK_ROW:
    MOV $B, 0x03

.OLED5_DRAW_CELL_BLOCK_COL:
    OLD $A
    STC
    SUB $B, 0x01
    JNZ .OLED5_DRAW_CELL_BLOCK_COL

    STC
    SUB $D, 0x01
    JNZ .OLED5_DRAW_CELL_BLOCK_ROW

    PUL $D
    PUL $B
    PUL $A
    RTS

OLED5_PRINT_READY_PROMPT:
    MOV $A, 0x52
    JSR OLED5_PUTC
    MOV $A, 0x45
    JSR OLED5_PUTC
    MOV $A, 0x41
    JSR OLED5_PUTC
    MOV $A, 0x44
    JSR OLED5_PUTC
    MOV $A, 0x59
    JSR OLED5_PUTC
    MOV $A, 0x3E
    JSR OLED5_PUTC
    RTS

OLED5_CURSOR_SHOW:
    JSR OLED5_DRAW_CURRENT_CELL_BLOCK_DIRECT
    RTS

OLED5_CURSOR_HIDE:
    JSR OLED5_CLEAR_CURRENT_CELL_DIRECT
    RTS

OLED5_TYPE_CHAR_WITH_CURSOR:
    MOV OLED_CHAR_TMP, $A
    JSR OLED5_CURSOR_HIDE
    MOV $A, OLED_CHAR_TMP
    JSR OLED5_PUTC
    JSR OLED5_CURSOR_SHOW
    RTS

OLED5_PRINT_HEX_NIBBLE:
    STC
    CMP $A, 0x0A
    JC .OLED5_HEX_LETTER

.OLED5_HEX_DIGIT:
    CLC
    ADD $A, 0x30
    JSR OLED5_PUTC
    RTS

.OLED5_HEX_LETTER:
    STC
    SUB $A, 0x0A
    CLC
    ADD $A, 0x41
    JSR OLED5_PUTC
    RTS

OLED5_PRINT_HEX_BYTE:
    MOV OLED_HEX_TMP, $A
    AND $A, 0xF0
    LSR $A
    LSR $A
    LSR $A
    LSR $A
    JSR OLED5_PRINT_HEX_NIBBLE

    MOV $A, OLED_HEX_TMP
    AND $A, 0x0F
    JSR OLED5_PRINT_HEX_NIBBLE
    RTS

OLED5_PRINT_HEX_WORD_CD:
    MOV OLED_HEX_WORD_LO, $C
    MOV OLED_HEX_WORD_HI, $D

    MOV $A, OLED_HEX_WORD_HI
    JSR OLED5_PRINT_HEX_BYTE

    MOV $A, OLED_HEX_WORD_LO
    JSR OLED5_PRINT_HEX_BYTE
    RTS
