; ==========================================================
; oled_text_4x6.asm
; ==========================================================
; Generated by make_oled_text_4x6_library.py
; SSD1325 compact 4x6 monitor text layer.
;
; Cell size:
;   4 pixels wide  = 2 grouped SSD1325 columns
;   7 pixels tall  = 6 font rows + 1 spacer row
;
; Pixel packing for OLED_INIT / A0h = 0x52:
;   left pixel  -> high nibble
;   right pixel -> low nibble
;
; Safe drawing area:
;   text rows use raw pixel rows 0 through 62
;   raw pixel row 63 is left unused by normal text
;
; API:
;   OLED4_SET_CURSOR
;   OLED4_DRAW_CHAR
;   OLED4_DRAW_STRING
;   OLED4_PUTC
;
; Calling convention:
;   OLED4_SET_CURSOR:
;       A = column
;       B = row
;
;   OLED4_DRAW_CHAR:
;       A = ASCII character
;
;   OLED4_DRAW_STRING:
;       CD = pointer to null-terminated RAM string
;       newline = 0x0A
; ==========================================================

; ---------- 4x6 terminal geometry ----------
OLED4_MAX_COLS         = 0x20
OLED4_MAX_ROWS         = 0x09
OLED4_LAST_COL         = 0x1F
OLED4_CELL_BYTES       = 0x02
OLED4_CELL_H           = 0x07
OLED4_DEFAULT_X        = 0x00
OLED4_DEFAULT_Y        = 0x00
OLED4_CLEAR_COLS       = 0x40
OLED4_CLEAR_ROWS       = 0x3F
OLED4_SAFE_MAX_RAW_ROW = 0x3E
OLED4_PENDING_WRAP     = 0x701F

OLED4_SET_CURSOR:
    ; in: A = col, B = row
    MOV OLED_CURSOR_COL, $A
    MOV OLED_CURSOR_ROW, $B
    MOV $A, 0x00
    MOV OLED4_PENDING_WRAP, $A
    RTS

OLED4_NEWLINE:
    MOV $A, 0x00
    MOV OLED_CURSOR_COL, $A
    MOV OLED4_PENDING_WRAP, $A

    MOV $A, OLED_CURSOR_ROW
    CLC
    NOP
    ADD $A, 0x01
    MOV OLED_CURSOR_ROW, $A

    STC
    NOP
    CMP $A, OLED4_MAX_ROWS
    JZ OLED4_NEWLINE_WRAP_TOP

    RTS

OLED4_NEWLINE_WRAP_TOP:
    MOV $A, 0x00
    MOV OLED_CURSOR_ROW, $A
    RTS

OLED4_ADVANCE_CURSOR:
    MOV $A, OLED_CURSOR_COL
    STC
    NOP
    CMP $A, OLED4_LAST_COL
    JZ OLED4_ADVANCE_CURSOR_PENDING

    CLC
    NOP
    ADD $A, 0x01
    MOV OLED_CURSOR_COL, $A
    RTS

OLED4_ADVANCE_CURSOR_PENDING:
    MOV $A, 0x01
    MOV OLED4_PENDING_WRAP, $A
    RTS

OLED4_INC_CD:
    CLC
    NOP
    ADD $C, 0x01
    JNC OLED4_INC_CD_DONE

    CLC
    NOP
    ADD $D, 0x01

OLED4_INC_CD_DONE:
    RTS

OLED4_DRAW_STRING:
OLED4_DRAW_STRING_LOOP:
    MOV $A, [$CD]

    STC
    NOP
    CMP $A, 0x00
    JZ OLED4_DRAW_STRING_DONE

    JSR OLED4_PUTC
    JSR OLED4_INC_CD
    JMP OLED4_DRAW_STRING_LOOP

OLED4_DRAW_STRING_DONE:
    RTS

OLED4_DRAW_CHAR:
    MOV OLED_CHAR_TMP, $A

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x20       ; SPACE
    JZ OLED4_CHAR_SPACE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x30       ; 0
    JZ OLED4_CHAR_DIGIT_0

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x31       ; 1
    JZ OLED4_CHAR_DIGIT_1

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x32       ; 2
    JZ OLED4_CHAR_DIGIT_2

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x33       ; 3
    JZ OLED4_CHAR_DIGIT_3

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x34       ; 4
    JZ OLED4_CHAR_DIGIT_4

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x35       ; 5
    JZ OLED4_CHAR_DIGIT_5

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x36       ; 6
    JZ OLED4_CHAR_DIGIT_6

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x37       ; 7
    JZ OLED4_CHAR_DIGIT_7

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x38       ; 8
    JZ OLED4_CHAR_DIGIT_8

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x39       ; 9
    JZ OLED4_CHAR_DIGIT_9

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x41       ; A
    JZ OLED4_CHAR_A

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x42       ; B
    JZ OLED4_CHAR_B

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x43       ; C
    JZ OLED4_CHAR_C

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x44       ; D
    JZ OLED4_CHAR_D

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x45       ; E
    JZ OLED4_CHAR_E

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x46       ; F
    JZ OLED4_CHAR_F

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x47       ; G
    JZ OLED4_CHAR_G

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x48       ; H
    JZ OLED4_CHAR_H

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x49       ; I
    JZ OLED4_CHAR_I

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x4A       ; J
    JZ OLED4_CHAR_J

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x4B       ; K
    JZ OLED4_CHAR_K

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x4C       ; L
    JZ OLED4_CHAR_L

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x4D       ; M
    JZ OLED4_CHAR_M

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x4E       ; N
    JZ OLED4_CHAR_N

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x4F       ; O
    JZ OLED4_CHAR_O

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x50       ; P
    JZ OLED4_CHAR_P

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x51       ; Q
    JZ OLED4_CHAR_Q

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x52       ; R
    JZ OLED4_CHAR_R

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x53       ; S
    JZ OLED4_CHAR_S

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x54       ; T
    JZ OLED4_CHAR_T

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x55       ; U
    JZ OLED4_CHAR_U

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x56       ; V
    JZ OLED4_CHAR_V

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x57       ; W
    JZ OLED4_CHAR_W

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x58       ; X
    JZ OLED4_CHAR_X

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x59       ; Y
    JZ OLED4_CHAR_Y

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x5A       ; Z
    JZ OLED4_CHAR_Z

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x21       ; !
    JZ OLED4_CHAR_EXCLAMATION

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x22       ; "
    JZ OLED4_CHAR_DOUBLE_QUOTE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x23       ; #
    JZ OLED4_CHAR_HASH

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x24       ; $
    JZ OLED4_CHAR_DOLLAR

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x25       ; %
    JZ OLED4_CHAR_PERCENT

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x26       ; &
    JZ OLED4_CHAR_AMPERSAND

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x27       ; '
    JZ OLED4_CHAR_APOSTROPHE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x28       ; (
    JZ OLED4_CHAR_LPAREN

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x29       ; )
    JZ OLED4_CHAR_RPAREN

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x2A       ; *
    JZ OLED4_CHAR_ASTERISK

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x2B       ; +
    JZ OLED4_CHAR_PLUS

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x2C       ; ,
    JZ OLED4_CHAR_COMMA

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x2D       ; -
    JZ OLED4_CHAR_DASH

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x2E       ; .
    JZ OLED4_CHAR_DOT

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x2F       ; /
    JZ OLED4_CHAR_SLASH

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x3A       ; :
    JZ OLED4_CHAR_COLON

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x3B       ; ;
    JZ OLED4_CHAR_SEMICOLON

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x3C       ; <
    JZ OLED4_CHAR_LT

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x3D       ; =
    JZ OLED4_CHAR_EQUALS

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x3E       ; >
    JZ OLED4_CHAR_GT

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x3F       ; ?
    JZ OLED4_CHAR_QUESTION

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x40       ; @
    JZ OLED4_CHAR_AT

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x5B       ; [
    JZ OLED4_CHAR_LBRACKET

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x5C       ; \
    JZ OLED4_CHAR_BACKSLASH

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x5D       ; ]
    JZ OLED4_CHAR_RBRACKET

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x5E       ; ^
    JZ OLED4_CHAR_CARET

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x5F       ; _
    JZ OLED4_CHAR_UNDERSCORE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x60       ; `
    JZ OLED4_CHAR_BACKTICK

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x7B       ; {
    JZ OLED4_CHAR_LBRACE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x7C       ; |
    JZ OLED4_CHAR_PIPE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x7D       ; }
    JZ OLED4_CHAR_RBRACE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x7E       ; ~
    JZ OLED4_CHAR_TILDE

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x61       ; a
    JZ OLED4_CHAR_A

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x62       ; b
    JZ OLED4_CHAR_B

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x63       ; c
    JZ OLED4_CHAR_C

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x64       ; d
    JZ OLED4_CHAR_D

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x65       ; e
    JZ OLED4_CHAR_E

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x66       ; f
    JZ OLED4_CHAR_F

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x67       ; g
    JZ OLED4_CHAR_G

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x68       ; h
    JZ OLED4_CHAR_H

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x69       ; i
    JZ OLED4_CHAR_I

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x6A       ; j
    JZ OLED4_CHAR_J

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x6B       ; k
    JZ OLED4_CHAR_K

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x6C       ; l
    JZ OLED4_CHAR_L

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x6D       ; m
    JZ OLED4_CHAR_M

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x6E       ; n
    JZ OLED4_CHAR_N

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x6F       ; o
    JZ OLED4_CHAR_O

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x70       ; p
    JZ OLED4_CHAR_P

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x71       ; q
    JZ OLED4_CHAR_Q

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x72       ; r
    JZ OLED4_CHAR_R

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x73       ; s
    JZ OLED4_CHAR_S

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x74       ; t
    JZ OLED4_CHAR_T

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x75       ; u
    JZ OLED4_CHAR_U

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x76       ; v
    JZ OLED4_CHAR_V

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x77       ; w
    JZ OLED4_CHAR_W

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x78       ; x
    JZ OLED4_CHAR_X

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x79       ; y
    JZ OLED4_CHAR_Y

    MOV $A, OLED_CHAR_TMP
    STC
    NOP
    CMP $A, 0x7A       ; z
    JZ OLED4_CHAR_Z

    JMP OLED4_CHAR_QUESTION

OLED4_COMPUTE_CURSOR_BASE:
    ; base grouped column = origin_x + col * 2
    MOV $A, OLED_TEXT_ORIGIN_X
    MOV $B, OLED_CURSOR_COL

OLED4_CURSOR_X_LOOP:
    STC
    NOP
    CMP $B, 0x00
    JZ OLED4_CURSOR_X_DONE

    CLC
    NOP
    ADD $A, 0x02

    STC
    NOP
    SUB $B, 0x01
    JMP OLED4_CURSOR_X_LOOP

OLED4_CURSOR_X_DONE:
    MOV OLED_GLYPH_BASE_X, $A

    ; base row = origin_y + row * 7
    MOV $A, OLED_TEXT_ORIGIN_Y
    MOV $B, OLED_CURSOR_ROW

OLED4_CURSOR_Y_LOOP:
    STC
    NOP
    CMP $B, 0x00
    JZ OLED4_CURSOR_Y_DONE

    CLC
    NOP
    ADD $A, 0x07

    STC
    NOP
    SUB $B, 0x01
    JMP OLED4_CURSOR_Y_LOOP

OLED4_CURSOR_Y_DONE:
    MOV OLED_GLYPH_BASE_Y, $A
    RTS

OLED4_RENDER_BEGIN:
    JSR OLED4_COMPUTE_CURSOR_BASE

    ; column window: 2 grouped columns
    MOV $A, 0x15
    OLC $A
    MOV $A, OLED_GLYPH_BASE_X
    OLC $A
    CLC
    NOP
    ADD $A, 0x01
    OLC $A

    ; row window: 7 pixel rows
    MOV $A, 0x75
    OLC $A
    MOV $A, OLED_GLYPH_BASE_Y
    OLC $A
    CLC
    NOP
    ADD $A, 0x06
    OLC $A

    MOV $A, 0x5C
    OLC $A
    RTS


; Character: SPACE (' ')
OLED4_CHAR_SPACE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 0
OLED4_CHAR_DIGIT_0:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 1
OLED4_CHAR_DIGIT_1:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 2
OLED4_CHAR_DIGIT_2:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 3
OLED4_CHAR_DIGIT_3:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 4
OLED4_CHAR_DIGIT_4:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 5
OLED4_CHAR_DIGIT_5:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 6
OLED4_CHAR_DIGIT_6:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 7
OLED4_CHAR_DIGIT_7:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 8
OLED4_CHAR_DIGIT_8:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: 9
OLED4_CHAR_DIGIT_9:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: A
OLED4_CHAR_A:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: B
OLED4_CHAR_B:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: C
OLED4_CHAR_C:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: D
OLED4_CHAR_D:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: E
OLED4_CHAR_E:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: F
OLED4_CHAR_F:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: G
OLED4_CHAR_G:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: H
OLED4_CHAR_H:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: I
OLED4_CHAR_I:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: J
OLED4_CHAR_J:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: K
OLED4_CHAR_K:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: L
OLED4_CHAR_L:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: M
OLED4_CHAR_M:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: N
OLED4_CHAR_N:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: O
OLED4_CHAR_O:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: P
OLED4_CHAR_P:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: Q
OLED4_CHAR_Q:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: R
OLED4_CHAR_R:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: S
OLED4_CHAR_S:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: T
OLED4_CHAR_T:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: U
OLED4_CHAR_U:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: V
OLED4_CHAR_V:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: W
OLED4_CHAR_W:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: X
OLED4_CHAR_X:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: Y
OLED4_CHAR_Y:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: Z
OLED4_CHAR_Z:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: !
OLED4_CHAR_EXCLAMATION:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: "
OLED4_CHAR_DOUBLE_QUOTE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: #
OLED4_CHAR_HASH:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: $
OLED4_CHAR_DOLLAR:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: %
OLED4_CHAR_PERCENT:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: &
OLED4_CHAR_AMPERSAND:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: '
OLED4_CHAR_APOSTROPHE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: (
OLED4_CHAR_LPAREN:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: )
OLED4_CHAR_RPAREN:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: *
OLED4_CHAR_ASTERISK:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: +
OLED4_CHAR_PLUS:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: ,
OLED4_CHAR_COMMA:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: -
OLED4_CHAR_DASH:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: .
OLED4_CHAR_DOT:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: /
OLED4_CHAR_SLASH:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: :
OLED4_CHAR_COLON:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: ;
OLED4_CHAR_SEMICOLON:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: <
OLED4_CHAR_LT:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: =
OLED4_CHAR_EQUALS:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: >
OLED4_CHAR_GT:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: ?
OLED4_CHAR_QUESTION:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: @
OLED4_CHAR_AT:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: [
OLED4_CHAR_LBRACKET:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: \
OLED4_CHAR_BACKSLASH:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: ]
OLED4_CHAR_RBRACKET:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: ^
OLED4_CHAR_CARET:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: _
OLED4_CHAR_UNDERSCORE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: `
OLED4_CHAR_BACKTICK:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: {
OLED4_CHAR_LBRACE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: |
OLED4_CHAR_PIPE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: }
OLED4_CHAR_RBRACE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xAA
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS

; Character: ~
OLED4_CHAR_TILDE:
    JSR OLED4_RENDER_BEGIN
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0x0A
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0xA0
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    MOV $A, 0x00
    OLD $A
    JSR OLED4_ADVANCE_CURSOR
    RTS
; ==========================================================
; Terminal helper routines
; ==========================================================

OLED4_HOME:
    MOV $A, 0x00
    MOV OLED_CURSOR_COL, $A
    MOV OLED_CURSOR_ROW, $A
    MOV OLED4_PENDING_WRAP, $A
    RTS

OLED4_SET_DEFAULT_ORIGIN:
    MOV $A, OLED4_DEFAULT_X
    MOV OLED_TEXT_ORIGIN_X, $A
    MOV $A, OLED4_DEFAULT_Y
    MOV OLED_TEXT_ORIGIN_Y, $A
    RTS

OLED4_CLEAR_TEXT_SCREEN:
    PSH $A
    PSH $B
    PSH $D

    MOV $A, 0x15
    OLC $A
    MOV $A, 0x00
    OLC $A
    MOV $A, 0x3F
    OLC $A

    MOV $A, 0x75
    OLC $A
    MOV $A, 0x00
    OLC $A
    MOV $A, OLED4_SAFE_MAX_RAW_ROW
    OLC $A

    MOV $A, 0x5C
    OLC $A

    MOV $A, 0x00
    MOV $D, OLED4_CLEAR_ROWS

.OLED4_CLEAR_TEXT_ROW:
    MOV $B, OLED4_CLEAR_COLS

.OLED4_CLEAR_TEXT_COL:
    OLD $A
    STC
    NOP
    SUB $B, 0x01
    JNZ .OLED4_CLEAR_TEXT_COL

    STC
    NOP
    SUB $D, 0x01
    JNZ .OLED4_CLEAR_TEXT_ROW

    PUL $D
    PUL $B
    PUL $A
    RTS

OLED4_PUTC:
    STC
    NOP
    CMP $A, 0x0A
    JZ OLED4_PUTC_NEWLINE

    STC
    NOP
    CMP $A, 0x0D
    JZ OLED4_PUTC_CR

    STC
    NOP
    CMP $A, 0x08
    JZ OLED4_PUTC_BACKSPACE

    MOV OLED_CHAR_TMP, $A
    JSR OLED4_APPLY_PENDING_WRAP
    MOV $A, OLED_CHAR_TMP
    JSR OLED4_DRAW_CHAR
    RTS

OLED4_PUTC_NEWLINE:
    JSR OLED4_NEWLINE
    RTS

OLED4_PUTC_CR:
    JSR OLED4_CARRIAGE_RETURN
    RTS

OLED4_PUTC_BACKSPACE:
    JSR OLED4_BACKSPACE
    RTS

OLED4_CARRIAGE_RETURN:
    MOV $A, 0x00
    MOV OLED_CURSOR_COL, $A
    MOV OLED4_PENDING_WRAP, $A
    RTS

OLED4_BACKSPACE:
    MOV $A, OLED4_PENDING_WRAP
    STC
    NOP
    CMP $A, 0x00
    JNZ .OLED4_BACKSPACE_CLEAR_CURRENT

    MOV $A, OLED_CURSOR_COL
    STC
    NOP
    CMP $A, 0x00
    JZ OLED4_BACKSPACE_DONE

    STC
    NOP
    SUB $A, 0x01
    MOV OLED_CURSOR_COL, $A

.OLED4_BACKSPACE_CLEAR_CURRENT:
    MOV $A, 0x00
    MOV OLED4_PENDING_WRAP, $A
    JSR OLED4_CLEAR_CURRENT_CELL_DIRECT

OLED4_BACKSPACE_DONE:
    RTS

OLED4_APPLY_PENDING_WRAP:
    MOV $A, OLED4_PENDING_WRAP
    STC
    NOP
    CMP $A, 0x00
    JNZ .OLED4_APPLY_WRAP

    RTS

.OLED4_APPLY_WRAP:
    MOV $A, 0x00
    MOV OLED4_PENDING_WRAP, $A
    MOV OLED_CURSOR_COL, $A

    MOV $A, OLED_CURSOR_ROW
    CLC
    NOP
    ADD $A, 0x01
    MOV OLED_CURSOR_ROW, $A

    STC
    NOP
    CMP $A, OLED4_MAX_ROWS
    JZ .OLED4_APPLY_WRAP_TOP

    RTS

.OLED4_APPLY_WRAP_TOP:
    MOV $A, 0x00
    MOV OLED_CURSOR_ROW, $A
    RTS

OLED4_CLEAR_CURRENT_CELL_DIRECT:
    PSH $A
    PSH $B
    PSH $D

    JSR OLED4_COMPUTE_CURSOR_BASE

    MOV $A, 0x15
    OLC $A
    MOV $A, OLED_GLYPH_BASE_X
    OLC $A
    CLC
    NOP
    ADD $A, 0x01
    OLC $A

    MOV $A, 0x75
    OLC $A
    MOV $A, OLED_GLYPH_BASE_Y
    OLC $A
    CLC
    NOP
    ADD $A, 0x06
    OLC $A

    MOV $A, 0x5C
    OLC $A
    MOV $A, 0x00
    MOV $D, OLED4_CELL_H

.OLED4_CLEAR_CELL_ROW:
    MOV $B, OLED4_CELL_BYTES

.OLED4_CLEAR_CELL_COL:
    OLD $A
    STC
    NOP
    SUB $B, 0x01
    JNZ .OLED4_CLEAR_CELL_COL

    STC
    NOP
    SUB $D, 0x01
    JNZ .OLED4_CLEAR_CELL_ROW

    PUL $D
    PUL $B
    PUL $A
    RTS

OLED4_DRAW_CURRENT_CELL_BLOCK_DIRECT:
    PSH $A
    PSH $B
    PSH $D

    JSR OLED4_COMPUTE_CURSOR_BASE

    MOV $A, 0x15
    OLC $A
    MOV $A, OLED_GLYPH_BASE_X
    OLC $A
    CLC
    NOP
    ADD $A, 0x01
    OLC $A

    MOV $A, 0x75
    OLC $A
    MOV $A, OLED_GLYPH_BASE_Y
    OLC $A
    CLC
    NOP
    ADD $A, 0x06
    OLC $A

    MOV $A, 0x5C
    OLC $A
    MOV $A, 0xFF
    MOV $D, OLED4_CELL_H

.OLED4_DRAW_CELL_BLOCK_ROW:
    MOV $B, OLED4_CELL_BYTES

.OLED4_DRAW_CELL_BLOCK_COL:
    OLD $A
    STC
    NOP
    SUB $B, 0x01
    JNZ .OLED4_DRAW_CELL_BLOCK_COL

    STC
    NOP
    SUB $D, 0x01
    JNZ .OLED4_DRAW_CELL_BLOCK_ROW

    PUL $D
    PUL $B
    PUL $A
    RTS

OLED4_CURSOR_SHOW:
    JSR OLED4_DRAW_CURRENT_CELL_BLOCK_DIRECT
    RTS

OLED4_CURSOR_HIDE:
    JSR OLED4_CLEAR_CURRENT_CELL_DIRECT
    RTS

OLED4_TYPE_CHAR_WITH_CURSOR:
    MOV OLED_CHAR_TMP, $A
    JSR OLED4_CURSOR_HIDE
    MOV $A, OLED_CHAR_TMP
    JSR OLED4_PUTC
    JSR OLED4_CURSOR_SHOW
    RTS

OLED4_PRINT_HEX_NIBBLE:
    STC
    NOP
    CMP $A, 0x0A
    JC .OLED4_HEX_LETTER

.OLED4_HEX_DIGIT:
    CLC
    NOP
    ADD $A, 0x30
    JSR OLED4_PUTC
    RTS

.OLED4_HEX_LETTER:
    STC
    NOP
    SUB $A, 0x0A
    CLC
    NOP
    ADD $A, 0x41
    JSR OLED4_PUTC
    RTS

OLED4_PRINT_HEX_BYTE:
    MOV OLED_HEX_TMP, $A
    AND $A, 0xF0
    LSR $A
    LSR $A
    LSR $A
    LSR $A
    JSR OLED4_PRINT_HEX_NIBBLE

    MOV $A, OLED_HEX_TMP
    AND $A, 0x0F
    JSR OLED4_PRINT_HEX_NIBBLE
    RTS

OLED4_PRINT_HEX_WORD_CD:
    MOV OLED_HEX_WORD_LO, $C
    MOV OLED_HEX_WORD_HI, $D

    MOV $A, OLED_HEX_WORD_HI
    JSR OLED4_PRINT_HEX_BYTE

    MOV $A, OLED_HEX_WORD_LO
    JSR OLED4_PRINT_HEX_BYTE
    RTS
